Name: PYTHON_Primitive_Lv1
IconPath: dekat.png
SoundPath: dekat.wav
Description: |
    Equipe de super Python avec des primitives
BrainsPackage: teams.python_primitive
ScriptImplementation: python
AgentsBrainClasses:
    WarBase: WarBase.py
    WarExplorer: WarExplorer.py
    WarRocketLauncher: WarRocketLauncher.py
    WarKamikaze: WarKamikaze.py
    WarEngineer: WarEngineer.py
    WarTurret: WarTurret.py
